package color

import (
	"strconv"
	"strings"

	"gitlab.com/ethanbakerdev/colors/css"
	"gitlab.com/ethanbakerdev/colors/sol"
)

/*
For future development with special escape code sequences
	ClearScreen = "\033[2J\033[H"
	ClearLine   = "\033[2K\033[G"
	CursorOff   = "\033[?25l"
	CursorOn    = "\033[?25h"
	StrikeOut   = "\033[9m"
*/

var colorReplacerAnsiSol *strings.Replacer
var colorReplacerAnsiCss *strings.Replacer

func init() {
	colorReplacerAnsiSol = strings.NewReplacer(
		sol.AnsiIndex["Base03"], "",
		sol.AnsiIndex["Base02"], "",
		sol.AnsiIndex["Base01"], "",
		sol.AnsiIndex["Base00"], "",
		sol.AnsiIndex["Base0"], "",
		sol.AnsiIndex["Base1"], "",
		sol.AnsiIndex["Base2"], "",
		sol.AnsiIndex["Base3"], "",
		sol.AnsiIndex["Yellow"], "",
		sol.AnsiIndex["Orange"], "",
		sol.AnsiIndex["Red"], "",
		sol.AnsiIndex["Magenta"], "",
		sol.AnsiIndex["Violet"], "",
		sol.AnsiIndex["Blue"], "",
		sol.AnsiIndex["Cyan"], "",
		sol.AnsiIndex["Green"], "",
		sol.AnsiIndex["Reset"], "",
	)

	colorReplacerAnsiCss = strings.NewReplacer(
		css.AnsiIndex["AliceBlue"], "",
		css.AnsiIndex["AntiqueWhite"], "",
		css.AnsiIndex["Aqua"], "",
		css.AnsiIndex["AquaMarine"], "",
		css.AnsiIndex["Azure"], "",
		css.AnsiIndex["Beige"], "",
		css.AnsiIndex["Bisque"], "",
		css.AnsiIndex["Black"], "",
		css.AnsiIndex["BlanchedAlmond"], "",
		css.AnsiIndex["Blue"], "",
		css.AnsiIndex["BlueViolet"], "",
		css.AnsiIndex["Brown"], "",
		css.AnsiIndex["BurlyWood"], "",
		css.AnsiIndex["CadetBlue"], "",
		css.AnsiIndex["Chartreuse"], "",
		css.AnsiIndex["Chocolate"], "",
		css.AnsiIndex["Coral"], "",
		css.AnsiIndex["CornFlowerBlue"], "",
		css.AnsiIndex["CornSilk"], "",
		css.AnsiIndex["Crimson"], "",
		css.AnsiIndex["Cyan"], "",
		css.AnsiIndex["DarkBlue"], "",
		css.AnsiIndex["DarkCyan"], "",
		css.AnsiIndex["DarkGoldenRod"], "",
		css.AnsiIndex["DarkGray"], "",
		css.AnsiIndex["DarkGreen"], "",
		css.AnsiIndex["DarkKhaki"], "",
		css.AnsiIndex["DarkMagenta"], "",
		css.AnsiIndex["DarkOliveGreen"], "",
		css.AnsiIndex["DarkOrange"], "",
		css.AnsiIndex["DarkOrchid"], "",
		css.AnsiIndex["DarkRed"], "",
		css.AnsiIndex["DarkSalmon"], "",
		css.AnsiIndex["DarkSeaGreen"], "",
		css.AnsiIndex["DarkSlateBlue"], "",
		css.AnsiIndex["DarkSlateGray"], "",
		css.AnsiIndex["DarkTurquoise"], "",
		css.AnsiIndex["DarkViolet"], "",
		css.AnsiIndex["DeepPink"], "",
		css.AnsiIndex["DeepSkyBlue"], "",
		css.AnsiIndex["DimGray"], "",
		css.AnsiIndex["DodgerBlue"], "",
		css.AnsiIndex["Firebrick"], "",
		css.AnsiIndex["FloralWhite"], "",
		css.AnsiIndex["ForestGreen"], "",
		css.AnsiIndex["Fuchsia"], "",
		css.AnsiIndex["Gainsboro"], "",
		css.AnsiIndex["GhostWhite"], "",
		css.AnsiIndex["Gold"], "",
		css.AnsiIndex["GoldenRod"], "",
		css.AnsiIndex["Gray"], "",
		css.AnsiIndex["Green"], "",
		css.AnsiIndex["GreenYellow"], "",
		css.AnsiIndex["Honeydew"], "",
		css.AnsiIndex["HotPink"], "",
		css.AnsiIndex["IndianRed"], "",
		css.AnsiIndex["Indigo"], "",
		css.AnsiIndex["Ivory"], "",
		css.AnsiIndex["Khaki"], "",
		css.AnsiIndex["Lavender"], "",
		css.AnsiIndex["LavenderBlush"], "",
		css.AnsiIndex["LawnGreen"], "",
		css.AnsiIndex["LemonChiffon"], "",
		css.AnsiIndex["LightBlue"], "",
		css.AnsiIndex["LightCoral"], "",
		css.AnsiIndex["LightCyan"], "",
		css.AnsiIndex["LightGoldenRodYellow"], "",
		css.AnsiIndex["LightGreen"], "",
		css.AnsiIndex["LightGray"], "",
		css.AnsiIndex["LightPink"], "",
		css.AnsiIndex["LightSalmon"], "",
		css.AnsiIndex["LightSeaGreen"], "",
		css.AnsiIndex["LightSkyBlue"], "",
		css.AnsiIndex["LightSlateGray"], "",
		css.AnsiIndex["LightSteelBlue"], "",
		css.AnsiIndex["LightYellow"], "",
		css.AnsiIndex["Lime"], "",
		css.AnsiIndex["LimeGreen"], "",
		css.AnsiIndex["Linen"], "",
		css.AnsiIndex["Magenta"], "",
		css.AnsiIndex["Maroon"], "",
		css.AnsiIndex["MediumAquaMarine"], "",
		css.AnsiIndex["MediumBlue"], "",
		css.AnsiIndex["MediumOrchid"], "",
		css.AnsiIndex["MediumPurple"], "",
		css.AnsiIndex["MediumSeaGreen"], "",
		css.AnsiIndex["MediumSlateBlue"], "",
		css.AnsiIndex["MediumSpringGreen"], "",
		css.AnsiIndex["MediumTurquoise"], "",
		css.AnsiIndex["MediumVioletRed"], "",
		css.AnsiIndex["MidnightBlue"], "",
		css.AnsiIndex["MintCream"], "",
		css.AnsiIndex["MistyRose"], "",
		css.AnsiIndex["Moccasin"], "",
		css.AnsiIndex["NavajoWhite"], "",
		css.AnsiIndex["Navy"], "",
		css.AnsiIndex["NavyBlue"], "",
		css.AnsiIndex["OldLace"], "",
		css.AnsiIndex["Olive"], "",
		css.AnsiIndex["OliveDrab"], "",
		css.AnsiIndex["Orange"], "",
		css.AnsiIndex["OrangeRed"], "",
		css.AnsiIndex["Orchid"], "",
		css.AnsiIndex["PaleGoldenRod"], "",
		css.AnsiIndex["PaleGreen"], "",
		css.AnsiIndex["PaleTurquoise"], "",
		css.AnsiIndex["PaleVioletRed"], "",
		css.AnsiIndex["PapayaWhip"], "",
		css.AnsiIndex["PeachPuff"], "",
		css.AnsiIndex["Peru"], "",
		css.AnsiIndex["Pink"], "",
		css.AnsiIndex["Plum"], "",
		css.AnsiIndex["PowderBlue"], "",
		css.AnsiIndex["Purple"], "",
		css.AnsiIndex["Red"], "",
		css.AnsiIndex["RosyBrown"], "",
		css.AnsiIndex["RoyalBlue"], "",
		css.AnsiIndex["SaddleBrown"], "",
		css.AnsiIndex["Salmon"], "",
		css.AnsiIndex["SandyBrown"], "",
		css.AnsiIndex["SeaGreen"], "",
		css.AnsiIndex["SeaShell"], "",
		css.AnsiIndex["Sienna"], "",
		css.AnsiIndex["Silver"], "",
		css.AnsiIndex["SkyBlue"], "",
		css.AnsiIndex["SlateBlue"], "",
		css.AnsiIndex["SlateGray"], "",
		css.AnsiIndex["Snow"], "",
		css.AnsiIndex["SpringGreen"], "",
		css.AnsiIndex["SteelBlue"], "",
		css.AnsiIndex["Tan"], "",
		css.AnsiIndex["Teal"], "",
		css.AnsiIndex["Thistle"], "",
		css.AnsiIndex["Tomato"], "",
		css.AnsiIndex["Turquoise"], "",
		css.AnsiIndex["Violet"], "",
		css.AnsiIndex["Wheat"], "",
		css.AnsiIndex["White"], "",
		css.AnsiIndex["WhiteSmoke"], "",
		css.AnsiIndex["Yellow"], "",
		css.AnsiIndex["YellowGreen"], "",
	)
}

// DecolorAnsiSol removes any of the sol ansi color escapes known to this package.
func DecolorAnsiSol(s string) string {
	return colorReplacerAnsiSol.Replace(s)
}

// DecolorAnsiiCss removes any of the css ansi color escapes known to this package.
func DecolorAnsiCss(s string) string {
	return colorReplacerAnsiCss.Replace(s)
}

// SearchAnsiIndex searches through a map of color names and their
// corresponding ansi escape codes to find the desired color
func SearchAnsiIndex(s string) Ansi {
	if val, ok := AnsiIndex[strings.ToLower(s)]; ok {
		return Ansi(string(val) + strings.ToLower(s))
	}
	return Ansi(string(s) + " is not a valid color. To see what colors are valid, run the sample? command.")
}

// PrintAnsiIndex prints the whole AnsiIndex out to the terminal
func PrintAnsiIndex() string {
	s := ""
	for k, v := range AnsiIndex {
		s = s + string(v) + k + "\n"
	}
	return s
}

// AnsiRGB creates a new ansi escape code based on an RGB input
func AnsiRGB(rgb RGB) string {
	s := "\x1b[38;2;" + strconv.FormatInt(int64(rgb.R), 10) + ";" + strconv.FormatInt(int64(rgb.G), 10) + ";" + strconv.FormatInt(int64(rgb.B), 10) + "m"
	return s
}

// AnsiRGBBackground creates a new background ansi escape code based on an RGB input
func AnsiRGBBackground(rgb RGB) Ansi {
	s := "\x1b[48;2;" + strconv.FormatInt(int64(rgb.R), 10) + ";" + strconv.FormatInt(int64(rgb.G), 10) + ";" + strconv.FormatInt(int64(rgb.B), 10) + "m"
	return Ansi(s)
}

// AnsiIndex is a map that contains every color in the package with its
// correlating ansi escape code
var AnsiIndex = map[string]Ansi{
	"sol.yellow":               DecimaltoAnsi(sol.Yellow),
	"sol.orange":               DecimaltoAnsi(sol.Orange),
	"sol.red":                  DecimaltoAnsi(sol.Red),
	"sol.magenta":              DecimaltoAnsi(sol.Magenta),
	"sol.violet":               DecimaltoAnsi(sol.Violet),
	"sol.blue":                 DecimaltoAnsi(sol.Blue),
	"sol.cyan":                 DecimaltoAnsi(sol.Cyan),
	"sol.green":                DecimaltoAnsi(sol.Green),
	"css.aliceblue":            DecimaltoAnsi(css.AliceBlue),
	"css.antiquewhite":         DecimaltoAnsi(css.AntiqueWhite),
	"css.aqua":                 DecimaltoAnsi(css.Aqua),
	"css.aquamarine":           DecimaltoAnsi(css.AquaMarine),
	"css.azure":                DecimaltoAnsi(css.Azure),
	"css.beige":                DecimaltoAnsi(css.Beige),
	"css.bisque":               DecimaltoAnsi(css.Bisque),
	"css.black":                DecimaltoAnsi(css.Black),
	"css.blanchedalmond":       DecimaltoAnsi(css.BlanchedAlmond),
	"css.blue":                 DecimaltoAnsi(css.Blue),
	"css.blueviolet":           DecimaltoAnsi(css.BlueViolet),
	"css.brown":                DecimaltoAnsi(css.Brown),
	"css.burlywood":            DecimaltoAnsi(css.BurlyWood),
	"css.cadetblue":            DecimaltoAnsi(css.CadetBlue),
	"css.chartreuse":           DecimaltoAnsi(css.Chartreuse),
	"css.chocolate":            DecimaltoAnsi(css.Chocolate),
	"css.coral":                DecimaltoAnsi(css.Coral),
	"css.cornflowerblue":       DecimaltoAnsi(css.CornFlowerBlue),
	"css.cornsilk":             DecimaltoAnsi(css.CornSilk),
	"css.crimson":              DecimaltoAnsi(css.Crimson),
	"css.cyan":                 DecimaltoAnsi(css.Cyan),
	"css.darkblue":             DecimaltoAnsi(css.DarkBlue),
	"css.darkcyan":             DecimaltoAnsi(css.DarkCyan),
	"css.darkgoldenrod":        DecimaltoAnsi(css.DarkGoldenRod),
	"css.darkgray":             DecimaltoAnsi(css.DarkGray),
	"css.darkgreen":            DecimaltoAnsi(css.DarkGreen),
	"css.darkkhaki":            DecimaltoAnsi(css.DarkKhaki),
	"css.darkmagenta":          DecimaltoAnsi(css.DarkMagenta),
	"css.darkolivegreen":       DecimaltoAnsi(css.DarkOliveGreen),
	"css.darkorange":           DecimaltoAnsi(css.DarkOrange),
	"css.darkorchid":           DecimaltoAnsi(css.DarkOrchid),
	"css.darkred":              DecimaltoAnsi(css.DarkRed),
	"css.darksalmon":           DecimaltoAnsi(css.DarkSalmon),
	"css.darkseagreen":         DecimaltoAnsi(css.DarkSeaGreen),
	"css.darkslateblue":        DecimaltoAnsi(css.DarkSlateBlue),
	"css.darkslategray":        DecimaltoAnsi(css.DarkSlateGray),
	"css.darkturquoise":        DecimaltoAnsi(css.DarkTurquoise),
	"css.darkviolet":           DecimaltoAnsi(css.DarkViolet),
	"css.deeppink":             DecimaltoAnsi(css.DeepPink),
	"css.deepskyblue":          DecimaltoAnsi(css.DeepSkyBlue),
	"css.dimgray":              DecimaltoAnsi(css.DimGray),
	"css.dodgerblue":           DecimaltoAnsi(css.DodgerBlue),
	"css.firebrick":            DecimaltoAnsi(css.Firebrick),
	"css.floralwhite":          DecimaltoAnsi(css.FloralWhite),
	"css.forestgreen":          DecimaltoAnsi(css.ForestGreen),
	"css.fuchsia":              DecimaltoAnsi(css.Fuchsia),
	"css.gainsboro":            DecimaltoAnsi(css.Gainsboro),
	"css.ghostwhite":           DecimaltoAnsi(css.GhostWhite),
	"css.gold":                 DecimaltoAnsi(css.Gold),
	"css.goldenrod":            DecimaltoAnsi(css.GoldenRod),
	"css.gray":                 DecimaltoAnsi(css.Gray),
	"css.green":                DecimaltoAnsi(css.Green),
	"css.greenyellow":          DecimaltoAnsi(css.GreenYellow),
	"css.honeydew":             DecimaltoAnsi(css.Honeydew),
	"css.hotpink":              DecimaltoAnsi(css.HotPink),
	"css.indianred":            DecimaltoAnsi(css.IndianRed),
	"css.indigo":               DecimaltoAnsi(css.Indigo),
	"css.ivory":                DecimaltoAnsi(css.Ivory),
	"css.khaki":                DecimaltoAnsi(css.Khaki),
	"css.lavender":             DecimaltoAnsi(css.Lavender),
	"css.lavenderblush":        DecimaltoAnsi(css.LavenderBlush),
	"css.lawngreen":            DecimaltoAnsi(css.LawnGreen),
	"css.lemonchiffon":         DecimaltoAnsi(css.LemonChiffon),
	"css.lightblue":            DecimaltoAnsi(css.LightBlue),
	"css.lightcoral":           DecimaltoAnsi(css.LightCoral),
	"css.lightcyan":            DecimaltoAnsi(css.LightCyan),
	"css.lightgoldenrodyellow": DecimaltoAnsi(css.LightGoldenRodYellow),
	"css.lightgreen":           DecimaltoAnsi(css.LightGreen),
	"css.lightgray":            DecimaltoAnsi(css.LightGray),
	"css.lightpink":            DecimaltoAnsi(css.LightPink),
	"css.lightsalmon":          DecimaltoAnsi(css.LightSalmon),
	"css.lightseagreen":        DecimaltoAnsi(css.LightSeaGreen),
	"css.lightskyblue":         DecimaltoAnsi(css.LightSkyBlue),
	"css.lightslategray":       DecimaltoAnsi(css.LightSlateGray),
	"css.lightsteelblue":       DecimaltoAnsi(css.LightSteelBlue),
	"css.lightyellow":          DecimaltoAnsi(css.LightYellow),
	"css.lime":                 DecimaltoAnsi(css.Lime),
	"css.limegreen":            DecimaltoAnsi(css.LimeGreen),
	"css.linen":                DecimaltoAnsi(css.Linen),
	"css.magenta":              DecimaltoAnsi(css.Magenta),
	"css.maroon":               DecimaltoAnsi(css.Maroon),
	"css.mediumaquamarine":     DecimaltoAnsi(css.MediumAquaMarine),
	"css.mediumblue":           DecimaltoAnsi(css.MediumBlue),
	"css.mediumorchid":         DecimaltoAnsi(css.MediumOrchid),
	"css.mediumpurple":         DecimaltoAnsi(css.MediumPurple),
	"css.mediumseagreen":       DecimaltoAnsi(css.MediumSeaGreen),
	"css.mediumslateblue":      DecimaltoAnsi(css.MediumSlateBlue),
	"css.mediumspringgreen":    DecimaltoAnsi(css.MediumSpringGreen),
	"css.mediumturquoise":      DecimaltoAnsi(css.MediumTurquoise),
	"css.mediumvioletred":      DecimaltoAnsi(css.MediumVioletRed),
	"css.midnightblue":         DecimaltoAnsi(css.MidnightBlue),
	"css.mintcream":            DecimaltoAnsi(css.MintCream),
	"css.mistyrose":            DecimaltoAnsi(css.MistyRose),
	"css.moccasin":             DecimaltoAnsi(css.Moccasin),
	"css.navajowhite":          DecimaltoAnsi(css.NavajoWhite),
	"css.navy":                 DecimaltoAnsi(css.Navy),
	"css.navyblue":             DecimaltoAnsi(css.NavyBlue),
	"css.oldlace":              DecimaltoAnsi(css.OldLace),
	"css.olive":                DecimaltoAnsi(css.Olive),
	"css.olivedrab":            DecimaltoAnsi(css.OliveDrab),
	"css.orange":               DecimaltoAnsi(css.Orange),
	"css.orangered":            DecimaltoAnsi(css.OrangeRed),
	"css.orchid":               DecimaltoAnsi(css.Orchid),
	"css.palegoldenrod":        DecimaltoAnsi(css.PaleGoldenRod),
	"css.palegreen":            DecimaltoAnsi(css.PaleGreen),
	"css.paleturquoise":        DecimaltoAnsi(css.PaleTurquoise),
	"css.palevioletred":        DecimaltoAnsi(css.PaleVioletRed),
	"css.papayawhip":           DecimaltoAnsi(css.PapayaWhip),
	"css.peachpuff":            DecimaltoAnsi(css.PeachPuff),
	"css.peru":                 DecimaltoAnsi(css.Peru),
	"css.pink":                 DecimaltoAnsi(css.Pink),
	"css.plum":                 DecimaltoAnsi(css.Plum),
	"css.powderblue":           DecimaltoAnsi(css.PowderBlue),
	"css.purple":               DecimaltoAnsi(css.Purple),
	"css.red":                  DecimaltoAnsi(css.RebeccaPurple),
	"css.rebeccapurple":        DecimaltoAnsi(css.Red),
	"css.rosybrown":            DecimaltoAnsi(css.RosyBrown),
	"css.royalblue":            DecimaltoAnsi(css.RoyalBlue),
	"css.saddlebrown":          DecimaltoAnsi(css.SaddleBrown),
	"css.salmon":               DecimaltoAnsi(css.Salmon),
	"css.sandybrown":           DecimaltoAnsi(css.SandyBrown),
	"css.seagreen":             DecimaltoAnsi(css.SeaGreen),
	"css.seashell":             DecimaltoAnsi(css.SeaShell),
	"css.sienna":               DecimaltoAnsi(css.Sienna),
	"css.silver":               DecimaltoAnsi(css.Silver),
	"css.skyblue":              DecimaltoAnsi(css.SkyBlue),
	"css.slateblue":            DecimaltoAnsi(css.SlateBlue),
	"css.slategray":            DecimaltoAnsi(css.SlateGray),
	"css.snow":                 DecimaltoAnsi(css.Snow),
	"css.springgreen":          DecimaltoAnsi(css.SpringGreen),
	"css.steelblue":            DecimaltoAnsi(css.SteelBlue),
	"css.tan":                  DecimaltoAnsi(css.Tan),
	"css.teal":                 DecimaltoAnsi(css.Teal),
	"css.thistle":              DecimaltoAnsi(css.Thistle),
	"css.tomato":               DecimaltoAnsi(css.Tomato),
	"css.turquoise":            DecimaltoAnsi(css.Turquoise),
	"css.violet":               DecimaltoAnsi(css.Violet),
	"css.wheat":                DecimaltoAnsi(css.Wheat),
	"css.white":                DecimaltoAnsi(css.White),
	"css.whitesmoke":           DecimaltoAnsi(css.WhiteSmoke),
	"css.yellow":               DecimaltoAnsi(css.Yellow),
	"css.yellowgreen":          DecimaltoAnsi(css.YellowGreen),
}

//Hex (int) colors

// SearchHexIndex searches through a map of color names and their
// corresponding ansi escape codes to find the desired color
func SearchHexIndex(s string) Decimal {
	if val, ok := HexIndex[strings.ToLower(s)]; ok {
		return val
	}
	return Decimal(0)
}

// PrintHexIndex prints the whole HexIndex out to the terminal
func PrintHexIndex() string {
	s := ""
	for k, v := range HexIndex {
		s = s + "#" + strconv.FormatInt(int64(v), 16) + k + "\n"
	}
	return s
}

// HexIndex is a map that contains every color in the package with its
// correlating decimal value
var HexIndex = map[string]Decimal{
	"sol.yellow":               sol.Yellow,
	"sol.orange":               sol.Orange,
	"sol.red":                  sol.Red,
	"sol.magenta":              sol.Magenta,
	"sol.violet":               sol.Violet,
	"sol.blue":                 sol.Blue,
	"sol.cyan":                 sol.Cyan,
	"sol.green":                sol.Green,
	"css.aliceblue":            css.AliceBlue,
	"css.antiquewhite":         css.AntiqueWhite,
	"css.aqua":                 css.Aqua,
	"css.aquamarine":           css.AquaMarine,
	"css.azure":                css.Azure,
	"css.beige":                css.Beige,
	"css.bisque":               css.Bisque,
	"css.black":                css.Black,
	"css.blanchedalmond":       css.BlanchedAlmond,
	"css.blue":                 css.Blue,
	"css.blueviolet":           css.BlueViolet,
	"css.brown":                css.Brown,
	"css.burlywood":            css.BurlyWood,
	"css.cadetblue":            css.CadetBlue,
	"css.chartreuse":           css.Chartreuse,
	"css.chocolate":            css.Chocolate,
	"css.coral":                css.Coral,
	"css.cornflowerblue":       css.CornFlowerBlue,
	"css.cornsilk":             css.CornSilk,
	"css.crimson":              css.Crimson,
	"css.cyan":                 css.Cyan,
	"css.darkblue":             css.DarkBlue,
	"css.darkcyan":             css.DarkCyan,
	"css.darkgoldenrod":        css.DarkGoldenRod,
	"css.darkgray":             css.DarkGray,
	"css.darkgreen":            css.DarkGreen,
	"css.darkkhaki":            css.DarkKhaki,
	"css.darkmagenta":          css.DarkMagenta,
	"css.darkolivegreen":       css.DarkOliveGreen,
	"css.darkorange":           css.DarkOrange,
	"css.darkorchid":           css.DarkOrchid,
	"css.darkred":              css.DarkRed,
	"css.darksalmon":           css.DarkSalmon,
	"css.darkseagreen":         css.DarkSeaGreen,
	"css.darkslateblue":        css.DarkSlateBlue,
	"css.darkslategray":        css.DarkSlateGray,
	"css.darkturquoise":        css.DarkTurquoise,
	"css.darkviolet":           css.DarkViolet,
	"css.deeppink":             css.DeepPink,
	"css.deepskyblue":          css.DeepSkyBlue,
	"css.dimgray":              css.DimGray,
	"css.dodgerblue":           css.DodgerBlue,
	"css.firebrick":            css.Firebrick,
	"css.floralwhite":          css.FloralWhite,
	"css.forestgreen":          css.ForestGreen,
	"css.fuchsia":              css.Fuchsia,
	"css.gainsboro":            css.Gainsboro,
	"css.ghostwhite":           css.GhostWhite,
	"css.gold":                 css.Gold,
	"css.goldenrod":            css.GoldenRod,
	"css.gray":                 css.Gray,
	"css.green":                css.Green,
	"css.greenyellow":          css.GreenYellow,
	"css.honeydew":             css.Honeydew,
	"css.hotpink":              css.HotPink,
	"css.indianred":            css.IndianRed,
	"css.indigo":               css.Indigo,
	"css.ivory":                css.Ivory,
	"css.khaki":                css.Khaki,
	"css.lavender":             css.Lavender,
	"css.lavenderblush":        css.LavenderBlush,
	"css.lawngreen":            css.LawnGreen,
	"css.lemonchiffon":         css.LemonChiffon,
	"css.lightblue":            css.LightBlue,
	"css.lightcoral":           css.LightCoral,
	"css.lightcyan":            css.LightCyan,
	"css.lightgoldenrodyellow": css.LightGoldenRodYellow,
	"css.lightgreen":           css.LightGreen,
	"css.lightgray":            css.LightGray,
	"css.lightpink":            css.LightPink,
	"css.lightsalmon":          css.LightSalmon,
	"css.lightseagreen":        css.LightSeaGreen,
	"css.lightskyblue":         css.LightSkyBlue,
	"css.lightslategray":       css.LightSlateGray,
	"css.lightsteelblue":       css.LightSteelBlue,
	"css.lightyellow":          css.LightYellow,
	"css.lime":                 css.Lime,
	"css.limegreen":            css.LimeGreen,
	"css.linen":                css.Linen,
	"css.magenta":              css.Magenta,
	"css.maroon":               css.Maroon,
	"css.mediumaquamarine":     css.MediumAquaMarine,
	"css.mediumblue":           css.MediumBlue,
	"css.mediumorchid":         css.MediumOrchid,
	"css.mediumpurple":         css.MediumPurple,
	"css.mediumseagreen":       css.MediumSeaGreen,
	"css.mediumslateblue":      css.MediumSlateBlue,
	"css.mediumspringgreen":    css.MediumSpringGreen,
	"css.mediumturquoise":      css.MediumTurquoise,
	"css.mediumvioletred":      css.MediumVioletRed,
	"css.midnightblue":         css.MidnightBlue,
	"css.mintcream":            css.MintCream,
	"css.mistyrose":            css.MistyRose,
	"css.moccasin":             css.Moccasin,
	"css.navajowhite":          css.NavajoWhite,
	"css.navy":                 css.Navy,
	"css.navyblue":             css.NavyBlue,
	"css.oldlace":              css.OldLace,
	"css.olive":                css.Olive,
	"css.olivedrab":            css.OliveDrab,
	"css.orange":               css.Orange,
	"css.orangered":            css.OrangeRed,
	"css.orchid":               css.Orchid,
	"css.palegoldenrod":        css.PaleGoldenRod,
	"css.palegreen":            css.PaleGreen,
	"css.paleturquoise":        css.PaleTurquoise,
	"css.palevioletred":        css.PaleVioletRed,
	"css.papayawhip":           css.PapayaWhip,
	"css.peachpuff":            css.PeachPuff,
	"css.peru":                 css.Peru,
	"css.pink":                 css.Pink,
	"css.plum":                 css.Plum,
	"css.powderblue":           css.PowderBlue,
	"css.purple":               css.Purple,
	"css.rebeccapurple":        css.RebeccaPurple,
	"css.red":                  css.Red,
	"css.rosybrown":            css.RosyBrown,
	"css.royalblue":            css.RoyalBlue,
	"css.saddlebrown":          css.SaddleBrown,
	"css.salmon":               css.Salmon,
	"css.sandybrown":           css.SandyBrown,
	"css.seagreen":             css.SeaGreen,
	"css.seashell":             css.SeaShell,
	"css.sienna":               css.Sienna,
	"css.silver":               css.Silver,
	"css.skyblue":              css.SkyBlue,
	"css.slateblue":            css.SlateBlue,
	"css.slategray":            css.SlateGray,
	"css.snow":                 css.Snow,
	"css.springgreen":          css.SpringGreen,
	"css.steelblue":            css.SteelBlue,
	"css.tan":                  css.Tan,
	"css.teal":                 css.Teal,
	"css.thistle":              css.Thistle,
	"css.tomato":               css.Tomato,
	"css.turquoise":            css.Turquoise,
	"css.violet":               css.Violet,
	"css.wheat":                css.Wheat,
	"css.white":                css.White,
	"css.whitesmoke":           css.WhiteSmoke,
	"css.yellow":               css.Yellow,
	"css.yellowgreen":          css.YellowGreen,
}
